Added a datePicker, made new expense show in the list and minor changes
L1keMagic/Outlay pull request #15
Opened 2022-04-23 21:55 UTC by Ololopololo

Made calendar an image again, moved it to the left, and changed back and done buttons color to darkblue

2022-04-23 22:35 UTC, L1keMagic requested changes

2022-04-23 22:35 UTC, L1keMagic commented on Outlay/Podfile.lock
> -COCOAPODS: 1.11.2
could you please remove this

2022-04-23 22:35 UTC, L1keMagic commented on Outlay/Outlay/NewExpense/NewExpenseViewController.swift
> +            // Fallback on earlier versions
could you please clarify what the logic will be executed it there is less iOS version used

2022-04-23 22:35 UTC, L1keMagic commented on Outlay/Outlay/NewExpense/NewExpenseViewController.swift
> +    @objc func dateChange(datePicker: UIDatePicker) {
could you please change method name to calendarDateChanged()

2022-04-23 22:35 UTC, L1keMagic commented on Outlay/Outlay/NewExpense/NewExpenseViewController.swift
> +    @objc func dateChange(datePicker: UIDatePicker) {
Also you can give another method name which fits better here

2022-04-25 10:04 UTC, Ololopololo commented on Outlay/Outlay/NewExpense/NewExpenseViewController.swift
> +            // Fallback on earlier versions
Actually we don't need it at all, so i'll just remove it.

2022-04-25 10:04 UTC, Ololopololo commented on Outlay/Outlay/NewExpense/NewExpenseViewController.swift
> +    @objc func dateChange(datePicker: UIDatePicker) {
Done

2022-04-25 10:11 UTC, L1keMagic requested changes

2022-04-25 10:11 UTC, L1keMagic commented on Outlay/Outlay/NewExpense/NewExpenseViewController.swift
> +    @objc func didExpenceDateCnahged(datePicker: UIDatePicker) {
could you please spell "expen**s**e" word correctly

2022-04-25 10:13 UTC, Ololopololo commented on Outlay/Outlay/NewExpense/NewExpenseViewController.swift
> +    @objc func didExpenceDateCnahged(datePicker: UIDatePicker) {
fixed

2022-04-25 10:16 UTC, L1keMagic commented on Outlay/Outlay/NewExpense/NewExpenseViewController.swift
> +    @objc func didExpenceDateCnahged(datePicker: UIDatePicker) {
I dont see any changes

2022-04-25 10:18 UTC, L1keMagic commented
approved

2022-04-25 10:18 UTC, L1keMagic approved these changes
approved

2022-04-25 10:19 UTC, merged