formatting budgets
L1keMagic/Outlay pull request #49
Opened 2022-09-16 10:28 UTC by Ololopololo

# Description

Short summary of the change and which issue is fixed:

changed available budget naming to free some space and set trailing

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

2022-09-22 18:06 UTC, L1keMagic requested changes

2022-09-22 18:06 UTC, L1keMagic commented on Outlay/Outlay/Home/HomeViewController.swift
> +        todayOutlayAvailableLabel.textColor = (todayBudget.rounded() - todaySpent().rounded()) < 0 ? .systemRed : .black
Take. look at "Free" label
https://developer.apple.com/design/human-interface-guidelines/foundations/color
![Simulator Screen Recording - iPhone 13 Pro - 2022-09-22 at 20 00 50](https://user-images.githubusercontent.com/42898732/191819326-763e79eb-162e-4dde-b118-2eb415d9efae.gif)

2022-09-22 18:06 UTC, L1keMagic commented on Outlay/Outlay/Supporting/Constants.swift
> +    static let outlayOverrunLabelText = "Overrun: "
Could you please just leave a "Budget", "Spent", "Overrun" in the constants and do string concatenation inside the view like outlayBudgetLabelText + ": ". It'd be easer to localize the app later

2022-09-23 13:46 UTC, Ololopololo commented
![image](https://user-images.githubusercontent.com/84727862/191974905-501700d8-7486-45ba-a10f-03b47205dace.png)

2022-09-23 14:47 UTC, L1keMagic requested changes

2022-09-23 14:47 UTC, L1keMagic commented on Outlay/Outlay/Extentions/DoubleExtensions.swift
> +import Foundation
it seems you forgot to upload changes from project.xworkspace file. because I can not capture this extension

2022-10-05 22:19 UTC, closed without merging